### ISSUE TITLE
Please Can you guide me in detail on how to use it?

### ISSUE THREAD

**Issue by lsirikh** [gircore/gir.core#1017] opened 2024-02-02 00:54 UTC
I've made and utilized Custom Control for WPF MVVM using GstSharp.Hotfix using GstSharp 1.18.x version. In particular, I borrowed a lot of gstreamer-d3d11-overlay and am developing it, but the phenomenon that programs continue to die due to memory-related issues occurs in a few specific cameras. I struggled to find it for a few days, but there was a limit to debugging due to the difficulty of accessing the original source GstSharp.Hotfix.

## Work environment
Window 10 pro, Visual Studio 2022

## Gstreamer Installation Environment
D:\gstreamer\1.0\msvc_x86: installing gstreamer-d3d11-overlay because it is a 32-bit-based library
D:\gstreamer\1.0\msvc_x86_64

## System Configuration History
1. 32bit Gstreamer
Variable name: GSTREAMER_1_0_ROOT_MSVC_X86
Variable value: D:\gstreamer\1.0\msvc_x86\

2. 64bit Gstreamer
Variable name: GSTREAMER_1_0_ROOT_MSVC_X86_64
Variable value: D:\gstreamer\1.0\msvc_x86_64\

3. Plugin Path
Variable name: GST_PLUGIN_SYSTEM_PATH
Variable value: D:\gstreamer\1.0\msvc_x86\lib\gstreamer-1.0

4. bin folder path settings
Variable name: PATH
Variable values: 
...thinking...
%GSTREAMER_1_0_ROOT_MSVC_X86%\bin;
%GSTREAMER_1_0_ROOT_MSVC_X86_64%\bin;

Originally GstSharp, but GstSharp.Hotfix was able to run the example right away, but GirCore.Gst-1.0 does not work with the following error message.

```
System.DllNotFoundException
  HResult=0x80131524
  Message=Unable to load DLL 'libgstreamer-1.0-0.dll' or one of its dependencies: Specified module not found. (0x8007007E)
  Source=<Cannot evaluate the exception source>
  StackTrace:
<Cannot evaluate the exception stack trace>
```

Is there anyone who can help?

My final purpose is to create a View component to demonstrate RTSP streaming using MVVM method Custom Control with WPF.

**Comment by badcel** [comment] 2024-02-02 04:46
This is not the `GstSharp` project but GirCore.

Please submit your issue to the [gstreamer project directly](https://gitlab.freedesktop.org/gstreamer/gstreamer/-/issues).

**Comment by badcel** [comment] 2024-02-02 04:56
Do you use a custom build gstramer? If yes this should be a duplicate of #963.

In short: GirCore nuget packages officially only support msys2 windows packages.

If you build your own GStreamer libraries, it is recommended to build your own GirCore binaries matching your version.

Details can be found in #963.

**Comment by lsirikh** [comment] 2024-02-02 05:35
> Do you use a custom build gstreamer? If yes this should be a duplicate of #963.
> 
> In short: GirCore nuget packages officially only support msys2 windows packages.
> 
> If you build your own GStreamer libraries, it is recommended to build your own GirCore binaries matching your version.
> 
> Details can be found in #963.

Thank you. I'll check and give it a try.

**Closed** 2024-02-05 16:04 UTC
